### PR TITLE
Rework/site redesign

### PR DESCRIPTION
**Pull request by joshuaHallee**
🌎 [Update has been staged for viewing here](https://fitdevs-redesign.netlify.app/)

⚠️ This update removes the dependency of Bootstrap since it is custom CSS. This may lead to design issues for expansion later since there is no framework, but bootstrap can be easily added back if needed.

❗ WE NEED CONTENT - Both Events and Testimonials need valid content before merging. Either comment out the code before launch, or launch with content.

👀 Updated README.md to include commonly used links found in our Discord.

This website update improves upon the existing design for usability. It allows for a navigation bar with social links, making for easier access. Shows community engagement through goals, events, testimonials, and curated Twitter embedded tweets.

Feedback is appreciated 😄

### CODE REVIEW

**Comment by Kyle-Kerlew** [comment]
Looks good. Only thing I could possibly think of is maybe having the theme colors defined as CSS variables, but I'm not sure it's necessary with the current design since the colors are only used once or twice

**Comment by katalystkat** [comment]
I actually agree with Kyle. Let's have a specific style guide that we can apply to all future fitdevs pages

**Comment by katalystkat** [comment]
Hi Josh, I'm going to go ahead and start adding testimonials & events such as tomorrow's twitter space. 

I'm thinking of editing the text under "Who We Are" to reflect your title. The text that I had in the accordion before, were tailored to answer specifically why/how/what fitdevs exists, not necessarily who we are.

**Comment by katalystkat** [comment]
Additional comments: 

1) I'd like to keep an accordion type element to specify why/how/what fitdevs exists etc. I think having a clear and defined mission statement, strategies, and defined examples of how we are achieving our goals is a very important element to our community that I'd like to continue to highlight. I don't want to attract a crowd of devs who are just here to hang out on discord. I'd like everyone who comes on to know the different aspects of #FitDevs that they can join in on & participate in. 

2) The twitter link should be directing individuals to see the #FitDevs query on twitter to highlight community tweets  instead of our @fit_devs page 

3) let's change "community progress" to Our Journey 

4) let's update the journey to include our twitter spaces held so far; i wonder how we can have a page to archive previous spaces so that community members that missed it can tune in afterwards 

5) I'm thinking of changing the 300+ members have joined, bc the # doesn't persuade people to join. Perhaps something among the lines of Join our community of 300+ developer accountability partners to go through this journey together? 

6)think I'll start a discussion on gh for events that we can start hosting! this is a lovely idea  

7) is there a way we can add more splashes of color in the background? Eg I have made vertical pages where different sections were alternating between white/theme color? 

WIll post more feedback as they come up! Thanks for the wonderful work so far Josh!

**Comment by joshuaHallee** [comment]
@katalystkat @Kyle-Kerlew 

A few comments / concerns on particular numbers.

1. Instead of an accordion that is closed / hiding content, could we instead go for an open section, similarly looking to an accordion, minus the functionality of open/close? 

4. I'm hesitant to add too much content to the timeline. It would extend the page a lot and viewers may stop scrolling hiding the events / testimonials / tweets. Do we have the content for an archive page, such as twitter space recordings?

7. We may want to launch how it currently is, and then go back through and do a 2nd revision and add colors. Just to cut down on scope / time till launch. I'll work on some designs to show you after.

**Comment by joshuaHallee** [comment]
🌎 [Update #2 has been staged for viewing here](https://fitdevs-redesign.netlify.app/)

This update addresses comments 1-7 made on Aug 4 by Kat. Copy/Content could use some work, but that's something that will have to be managed after merge.

@katalystkat @Kyle-Kerlew

**Pull request merged**
